### ISSUE TITLE
exited processes shown as zombies

### ISSUE THREAD

**Issue by muralikodali** [orhun/zkill#11]
I am on Arch Linux and using alacritty as my terminal.

when i executed "zps -l" , it is listing all exited processes from terminal as zombies. If such a process is killed using "zps -p", terminal and tmux sessions are closed.

A screenshot of list of processes shown as zombies : 

![screenshot_20210121111543](https://user-images.githubusercontent.com/11482766/105285971-6bd4b680-5bdb-11eb-94e2-556d075f4180.png)

**Comment by orhun** [comment]
Hey,
What's the problem here? This is exactly what you will see if you run something like `ps aux | grep 'Z'`.
They are zombies.

**Comment by muralikodali** [comment]
Just to show executed shell processes, i have attached the above picture. Actual problem is , when i execute "zps -p", terminal and tmux sessions are closed.

**Comment by orhun** [comment]
It's probably about the [TODO#2](https://github.com/orhun/zps#todos). Unfortunately it's not implemented yet.
